export enum SR_STATUS {
    SUBMITTED = "OPEN",
    ASSIGNED = "ASSIGNED",
    IN_PROGRESS = "IN_PROGRESS",
    CLOSED = "CLOSED",
    REJECTED = "REJECTED"
}

export const TRANSITION_MAP: Record<string, string[]> = {
    [SR_STATUS.SUBMITTED]: [SR_STATUS.ASSIGNED, SR_STATUS.REJECTED],
    [SR_STATUS.ASSIGNED]: [SR_STATUS.IN_PROGRESS, SR_STATUS.REJECTED],
    [SR_STATUS.IN_PROGRESS]: [SR_STATUS.CLOSED, SR_STATUS.REJECTED],
    [SR_STATUS.CLOSED]: [],
    [SR_STATUS.REJECTED]: []
};
